version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8087:80"
    depends_on:
      - mysql

  php1:
    build:
      context: ./site1
    container_name: php1
    working_dir: /var/www/html
    volumes:
      - ./site1:/var/www/html
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql
    command: >
      sh -c "
        cp .env.example .env &&
        composer install &&
        npm install &&
        npm run build &&
        php artisan key:generate &&
        php artisan migrate:fresh --seed &&
        php-fpm
      "

  php2:
    build:
      context: ./site2
    container_name: php2
    working_dir: /var/www/html
    volumes:
      - ./site2:/var/www/html
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql
    command: >
      sh -c "
        cp .env.example .env &&
        composer install &&
        npm install &&
        npm run build &&
        php artisan key:generate &&
        php-fpm
      "

  nginx1:
    image: nginx:latest
    container_name: nginx1
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./site1:/var/www/html
    depends_on:
      - php1

  nginx2:
    image: nginx:latest
    container_name: nginx2
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./site2:/var/www/html
    depends_on:
      - php2

volumes:
  mysql_data:
